version: "3.8"

services:
  
  postgresdb:
    image: postgres:alpine
    restart: always
    volumes:
      - SP_POSTGRES_DB:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - PGDATA=/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  server:
    depends_on:
        - postgresdb  
    image: ${HUB_URL}/${APP_NAME_BACKEND}:${APP_VERSION}
    ports:
      - ${NODE_PORT:-5000}:${NODE_PORT:-5000}
    env_file: 
      - .env


volumes:
  SP_POSTGRES_DB:
